INSERT INTO AUTHOR (NAME) VALUES ('Martin Fowler');
INSERT INTO AUTHOR (NAME) VALUES ('Robert C. Martin');
INSERT INTO AUTHOR (NAME) VALUES ('Joshua Bloch');

INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Refactoring', (SELECT ID FROM AUTHOR WHERE NAME = 'Martin Fowler'));
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Clean Code', (SELECT ID FROM AUTHOR WHERE NAME = 'Robert C. Martin'));
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Effective Java', (SELECT ID FROM AUTHOR WHERE NAME = 'Joshua Bloch'));
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Clean Architecture', (SELECT ID FROM AUTHOR WHERE NAME = 'Robert C. Martin'));
