server.port=8091
# Choix du client HTTP: feign (default) ou http-exchange
books.client=feign
# URL du service BookApplication (utilisée par Feign et HttpExchange)
bookManagement.url=http://localhost:8092
