version: '3.8'
services:
  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "61616:61616" # Broker port
      - "8161:8161"   # Web console
    environment:
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin